services:
  zenproxy-server:
    image: crushry/zenproxy-server:latest
    container_name: zenproxy-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config/config.toml:/app/config.toml
      - ./data:/app/data
    environment:
      - RUST_LOG=zenproxy=info,tower_http=info
